//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PvzLauncherRemake.I18N {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageSettings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PvzLauncherRemake.I18N.PageSettings", typeof(PageSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string General_Custom {
            get {
                return ResourceManager.GetString("General_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string General_Default {
            get {
                return ResourceManager.GetString("General_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string General_Enabled {
            get {
                return ResourceManager.GetString("General_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string General_Operate {
            get {
                return ResourceManager.GetString("General_Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string General_Reset {
            get {
                return ResourceManager.GetString("General_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string General_Select {
            get {
                return ResourceManager.GetString("General_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance {
            get {
                return ResourceManager.GetString("Launcher_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景: 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_Background {
            get {
                return ResourceManager.GetString("Launcher_Appearance_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回声洞: 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_EchoCave {
            get {
                return ResourceManager.GetString("Launcher_Appearance_EchoCave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_Language {
            get {
                return ResourceManager.GetString("Launcher_Appearance_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航栏位置: 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_NavViewLocation {
            get {
                return ResourceManager.GetString("Launcher_Appearance_NavViewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左侧 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_NavViewLocation_Left {
            get {
                return ResourceManager.GetString("Launcher_Appearance_NavViewLocation_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_NavViewLocation_Top {
            get {
                return ResourceManager.GetString("Launcher_Appearance_NavViewLocation_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题: 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_Theme {
            get {
                return ResourceManager.GetString("Launcher_Appearance_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑暗 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_Theme_Dark {
            get {
                return ResourceManager.GetString("Launcher_Appearance_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明亮 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_Theme_Light {
            get {
                return ResourceManager.GetString("Launcher_Appearance_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题图片: 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_TitleImage {
            get {
                return ResourceManager.GetString("Launcher_Appearance_TitleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口标题: 的本地化字符串。
        /// </summary>
        public static string Launcher_Appearance_WindowTitle {
            get {
                return ResourceManager.GetString("Launcher_Appearance_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知 的本地化字符串。
        /// </summary>
        public static string Launcher_Notification {
            get {
                return ResourceManager.GetString("Launcher_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载通知: 的本地化字符串。
        /// </summary>
        public static string Launcher_Notification_DownloadNotice {
            get {
                return ResourceManager.GetString("Launcher_Notification_DownloadNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏下载通知 的本地化字符串。
        /// </summary>
        public static string Launcher_Notification_DownloadNotice_Game {
            get {
                return ResourceManager.GetString("Launcher_Notification_DownloadNotice_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改器下载通知 的本地化字符串。
        /// </summary>
        public static string Launcher_Notification_DownloadNotice_Trainer {
            get {
                return ResourceManager.GetString("Launcher_Notification_DownloadNotice_Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏启动后操作: 的本地化字符串。
        /// </summary>
        public static string Launcher_Operate_LaunchOperate {
            get {
                return ResourceManager.GetString("Launcher_Operate_LaunchOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器关闭 的本地化字符串。
        /// </summary>
        public static string Launcher_Operate_LaunchOperate_Close {
            get {
                return ResourceManager.GetString("Launcher_Operate_LaunchOperate_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器隐藏，等待游戏结束后显示 的本地化字符串。
        /// </summary>
        public static string Launcher_Operate_LaunchOperate_HideAndShow {
            get {
                return ResourceManager.GetString("Launcher_Operate_LaunchOperate_HideAndShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不执行任何操作 的本地化字符串。
        /// </summary>
        public static string Launcher_Operate_LaunchOperate_None {
            get {
                return ResourceManager.GetString("Launcher_Operate_LaunchOperate_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 储存 的本地化字符串。
        /// </summary>
        public static string Launcher_Storage {
            get {
                return ResourceManager.GetString("Launcher_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载缓存: 的本地化字符串。
        /// </summary>
        public static string Launcher_Storage_DownloadCache {
            get {
                return ResourceManager.GetString("Launcher_Storage_DownloadCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理 的本地化字符串。
        /// </summary>
        public static string Launcher_Storage_DownloadCache_Clear {
            get {
                return ResourceManager.GetString("Launcher_Storage_DownloadCache_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Launcher_Update {
            get {
                return ResourceManager.GetString("Launcher_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新通道: 的本地化字符串。
        /// </summary>
        public static string Launcher_Update_Channel {
            get {
                return ResourceManager.GetString("Launcher_Update_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测更新: 的本地化字符串。
        /// </summary>
        public static string Launcher_Update_CheckUpdate {
            get {
                return ResourceManager.GetString("Launcher_Update_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测 的本地化字符串。
        /// </summary>
        public static string Launcher_Update_CheckUpdate_Check {
            get {
                return ResourceManager.GetString("Launcher_Update_CheckUpdate_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时检查更新: 的本地化字符串。
        /// </summary>
        public static string Launcher_Update_StartUpCheck {
            get {
                return ResourceManager.GetString("Launcher_Update_StartUpCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏设置 的本地化字符串。
        /// </summary>
        public static string Tab_GameSettings {
            get {
                return ResourceManager.GetString("Tab_GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器设置 的本地化字符串。
        /// </summary>
        public static string Tab_LauncherSettings {
            get {
                return ResourceManager.GetString("Tab_LauncherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档设置 的本地化字符串。
        /// </summary>
        public static string Tab_SaveSettings {
            get {
                return ResourceManager.GetString("Tab_SaveSettings", resourceCulture);
            }
        }
    }
}
