//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PvzLauncherRemake.I18N {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageSettings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PvzLauncherRemake.I18N.PageSettings", typeof(PageSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景: 的本地化字符串。
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测 的本地化字符串。
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测更新: 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除存档 的本地化字符串。
        /// </summary>
        public static string DeleteSave {
            get {
                return ResourceManager.GetString("DeleteSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载缓存: 的本地化字符串。
        /// </summary>
        public static string DownloadCache {
            get {
                return ResourceManager.GetString("DownloadCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理 的本地化字符串。
        /// </summary>
        public static string DownloadCache_Clear {
            get {
                return ResourceManager.GetString("DownloadCache_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载通知: 的本地化字符串。
        /// </summary>
        public static string DownloadNotice {
            get {
                return ResourceManager.GetString("DownloadNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回声洞: 的本地化字符串。
        /// </summary>
        public static string EchoCave {
            get {
                return ResourceManager.GetString("EchoCave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制全屏 的本地化字符串。
        /// </summary>
        public static string ForceFullScreen {
            get {
                return ResourceManager.GetString("ForceFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制窗口化 的本地化字符串。
        /// </summary>
        public static string ForceWindowed {
            get {
                return ResourceManager.GetString("ForceWindowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏: 的本地化字符串。
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏配置 的本地化字符串。
        /// </summary>
        public static string GameConfig {
            get {
                return ResourceManager.GetString("GameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏设置 的本地化字符串。
        /// </summary>
        public static string GameSettings {
            get {
                return ResourceManager.GetString("GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器关闭 的本地化字符串。
        /// </summary>
        public static string LaunchClose {
            get {
                return ResourceManager.GetString("LaunchClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器设置 的本地化字符串。
        /// </summary>
        public static string LauncherSettings {
            get {
                return ResourceManager.GetString("LauncherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器隐藏，等待游戏结束后显示 的本地化字符串。
        /// </summary>
        public static string LaunchHideAndShow {
            get {
                return ResourceManager.GetString("LaunchHideAndShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不执行任何操作 的本地化字符串。
        /// </summary>
        public static string LaunchNone {
            get {
                return ResourceManager.GetString("LaunchNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏启动后操作: 的本地化字符串。
        /// </summary>
        public static string LaunchOperate {
            get {
                return ResourceManager.GetString("LaunchOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左上角 的本地化字符串。
        /// </summary>
        public static string LeftTop {
            get {
                return ResourceManager.GetString("LeftTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置: 的本地化字符串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档迁移 的本地化字符串。
        /// </summary>
        public static string MoveSave {
            get {
                return ResourceManager.GetString("MoveSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航栏位置: 的本地化字符串。
        /// </summary>
        public static string NavViewLocation {
            get {
                return ResourceManager.GetString("NavViewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左侧 的本地化字符串。
        /// </summary>
        public static string NavViewLocation_Left {
            get {
                return ResourceManager.GetString("NavViewLocation_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部 的本地化字符串。
        /// </summary>
        public static string NavViewLocation_Top {
            get {
                return ResourceManager.GetString("NavViewLocation_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏下载通知 的本地化字符串。
        /// </summary>
        public static string NoticeGame {
            get {
                return ResourceManager.GetString("NoticeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改器下载通知 的本地化字符串。
        /// </summary>
        public static string NoticeTrainer {
            get {
                return ResourceManager.GetString("NoticeTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知 的本地化字符串。
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Operate {
            get {
                return ResourceManager.GetString("Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档隔离 的本地化字符串。
        /// </summary>
        public static string SaveIsolation {
            get {
                return ResourceManager.GetString("SaveIsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档设置 的本地化字符串。
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时检查更新: 的本地化字符串。
        /// </summary>
        public static string StartUpCheck {
            get {
                return ResourceManager.GetString("StartUpCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 储存 的本地化字符串。
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题: 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑暗 的本地化字符串。
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明亮 的本地化字符串。
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题图片: 的本地化字符串。
        /// </summary>
        public static string TitleImage {
            get {
                return ResourceManager.GetString("TitleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新通道: 的本地化字符串。
        /// </summary>
        public static string UpdateChannel {
            get {
                return ResourceManager.GetString("UpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口标题: 的本地化字符串。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
